import {
  ArrowsClockwise,
  BookmarkSimple,
  Books,
  Buildings,
  ChartBar,
  CreditCard,
  FileText,
  Gavel,
  Package,
  Receipt,
  Scales,
  Scroll,
  ShoppingCart,
  Stack,
  Truck,
  UsersThree,
  Wallet,
  type Icon,
} from "@phosphor-icons/react"

import type { NavAreaKey } from "@/lib/permissions"

export const NAV_ICONS: Record<NavAreaKey, Icon> = {
  "purchase-requests": FileText,
  "purchase-orders": ShoppingCart,
  receipts: Truck,
  conferral: Scales,
  payables: Wallet,
  "service-invoices": Receipt,
  "recurring-contracts": ArrowsClockwise,
  "cost-centers": Stack,
  "approval-rules": Gavel,
  suppliers: Package,
  categories: BookmarkSimple,
  "chart-accounts": Books,
  members: UsersThree,
  "audit-logs": Scroll,
  analytics: ChartBar,
  billing: CreditCard,
  company: Buildings,
}
